version: '3.8'

services:
  web:
    image: odoo:17.0
    container_name: odoo-docker-web-1
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo_password
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: odoo-docker-db-1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo_password
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
